project:
  type: book

book:
  title: "extradocs"
  author: "Penelope Yong"
  date: "2024-11-18"
  chapters:
    - index.qmd
    - src/ad.qmd
    - src/linear.qmd
    - src/submodel.qmd

format:
  html:
    theme: cosmo
